/* Generated by cbindgen — do not edit manually */
/* Warning: this file is autogenerated by cbindgen. Do not modify this manually. */

#ifndef DEDUPO_FFI_H
#define DEDUPO_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque engine handle.
 */
typedef struct Engine Engine;

/**
 * Create a new engine instance.
 * The caller must free the returned pointer with `dedupo_engine_free`.
 */
struct Engine *dedupo_engine_create(const char *db_path);

/**
 * Free an engine instance.
 */
void dedupo_engine_free(struct Engine *engine);

/**
 * Add a scan target path.
 * Returns 0 on success, -1 on failure.
 */
int32_t dedupo_add_scan_path(struct Engine *engine, const char *path);

/**
 * Start an asynchronous scan.
 * Returns 0 on success, -1 on failure, 1 if cancelled.
 */
int32_t dedupo_scan_start(struct Engine *engine,
                          void (*progress_cb)(uint64_t, uint64_t, int32_t, void*),
                          void *context);

/**
 * Cancel an ongoing scan.
 */
void dedupo_scan_cancel(struct Engine *engine);

/**
 * Get the number of duplicate groups found.
 */
uint64_t dedupo_get_group_count(struct Engine *engine);

/**
 * Get a duplicate group by index as a JSON string.
 * The caller must free the returned string with `dedupo_free_string`.
 */
char *dedupo_get_group(struct Engine *engine, uint64_t index);

/**
 * Free a string allocated by the Rust engine.
 */
void dedupo_free_string(char *s);

/**
 * Move a file to the system trash.
 * Returns 0 on success, -1 on failure.
 */
int32_t dedupo_trash_file(const char *path);

#endif /* DEDUPO_FFI_H */
