/* Generated by cbindgen — do not edit manually */

#ifndef DEDUPO_FFI_H
#define DEDUPO_FFI_H

/* Warning: this file is autogenerated by cbindgen. Do not modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The main engine that coordinates scanning and deduplication.
 */
typedef struct Engine Engine;

/**
 * Progress callback type.
 *
 * Parameters: scanned_count, total_estimated, phase (as i32), user context
 */
typedef void (*ProgressCallback)(uint64_t, uint64_t, int32_t, void*);

/**
 * Create a new engine instance.
 *
 * # Safety
 * `db_path` must be a valid null-terminated C string.
 * The caller must free the returned pointer with `dedupo_engine_free`.
 */
struct Engine *dedupo_engine_create(const char *db_path);

/**
 * Free an engine instance.
 *
 * # Safety
 * `engine` must be a valid pointer returned by `dedupo_engine_create`,
 * or null (in which case this is a no-op).
 */
void dedupo_engine_free(struct Engine *engine);

/**
 * Add a scan target path.
 *
 * Returns 0 on success, -1 on failure.
 *
 * # Safety
 * Both `engine` and `path` must be valid pointers.
 */
int dedupo_add_scan_path(struct Engine *engine, const char *path);

/**
 * Clear all scan paths.
 *
 * Call this before adding new paths for a fresh scan.
 *
 * # Safety
 * `engine` must be a valid pointer.
 */
void dedupo_clear_scan_paths(struct Engine *engine);

/**
 * Start an asynchronous scan.
 *
 * The progress callback is invoked periodically with scan updates.
 * Returns 0 on success, -1 on failure, 1 if cancelled.
 *
 * # Safety
 * `engine` must be a valid pointer. `context` is passed through to the callback.
 */
int dedupo_scan_start(struct Engine *engine, ProgressCallback progress_cb, void *context);

/**
 * Cancel an ongoing scan.
 *
 * # Safety
 * `engine` must be a valid pointer.
 */
void dedupo_scan_cancel(struct Engine *engine);

/**
 * Get the number of duplicate groups found.
 *
 * # Safety
 * `engine` must be a valid pointer.
 */
uint64_t dedupo_get_group_count(struct Engine *engine);

/**
 * Get a duplicate group by index as a JSON string.
 *
 * Returns null if the index is out of range.
 * The caller must free the returned string with `dedupo_free_string`.
 *
 * # Safety
 * `engine` must be a valid pointer.
 */
char *dedupo_get_group(struct Engine *engine, uint64_t index);

/**
 * Free a string allocated by the Rust engine.
 *
 * # Safety
 * `s` must be a pointer returned by a `dedupo_get_*` function, or null.
 */
void dedupo_free_string(char *s);

/**
 * Move a file to the system trash.
 *
 * Returns 0 on success, -1 on failure.
 *
 * # Safety
 * `path` must be a valid null-terminated C string.
 */
int dedupo_trash_file(const char *path);

#endif  /* DEDUPO_FFI_H */
